<?php

/**
 * @file
 * Drupal module for downloading groups of files.
 */

define('ZIPCART_PATH_ADD', 'zipcart/add');
define('ZIPCART_PATH_GET', 'zipcart/get');

/**
 * Implements hook_menu().
 */
function zipcart_menu() {
  $items['admin/settings/zipcart'] = array(
    'page callback' => 'drupal_get_form',
    'page arguments' => array('zipcart_settings_form'),
    'title' => 'ZipCart',
    'description' => 'Configure Zip settings for ZipCart',
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'zipcart.admin.inc',
  );
  $items[ZIPCART_PATH_ADD] = array(
    'page callback' => 'zipcart_add_file_to_cart',
    'page arguments' => array(FALSE),
    'title' => 'Add file to Download Cart',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access zipcart downloads'),
  );
  $items[ZIPCART_PATH_ADD . '/AJAX'] = array(
    'page callback' => 'zipcart_add_file_to_cart',
    'page arguments' => array(TRUE),
    'title' => 'Add file to Download Cart',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access zipcart downloads'),
  );
  $items[ZIPCART_PATH_GET] = array(
    'page callback' => 'zipcart_get_zip',
    'title' => 'Download Cart Files',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access zipcart downloads'),
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function zipcart_theme($existing, $type, $theme, $path) {
  return array(
    'zipcart_block_downloads' => array(
      'template' => 'zipcart-block-downloads',
      'arguments' => array(
        'count' => 0,
        'files' => NULL,
      ),
    ),
    'zipcart_download' => array(
      'arguments' => array(
        'text' => 'Download',
        'path' => NULL,
        'options' => array(),
      ),
    ),
  );
}

/**
 * Implements hook_perm().
 */
function zipcart_perm() {
  return array(
    'access zipcart downloads',
  );
}

/**
 * Implements hook_block().
 */
function zipcart_block($op = 'list', $delta = 0, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks[0] = array(
        'info'  => t('ZipCart Downloads'),
        'cache' => BLOCK_NO_CACHE,
      );
      return $blocks;
    case 'view':
      if (user_access('access zipcart downloads')) {
        switch ($delta) {
          case '0':
            $block = array(
              'subject' => t('My Downloads'),
              'content' => zipcart_block_content(),
            );
            return $block;
        }
      }
    case 'configure':
    case 'save':
      return;
  }
}

/**
 * Return block content for zipcart block.
 */
function zipcart_block_content() {
  $count = (!empty($_SESSION['zipcart']['files'])) ? count($_SESSION['zipcart']['files']) : 0;
  $files = (!empty($_SESSION['zipcart']['files'])) ? $_SESSION['zipcart']['files'] : NULL;
  return theme('zipcart_block_downloads', $count, $files);
}

/**
 * Implements hook_zipmethods().
 *
 * Original intent was to provide PECL and external methods as well, but it
 * seems everyone using the module is getting by fine with PHP's builtin
 * ZipArchive. If you want to implement custom rar-bz2-rot13 file scruncher,
 * add an entry to this array.
 */
function zipcart_zipmethods() {
  $methods['zip_builtin'] = array(
    'title'    => 'PHP Zip extension',
    'callback' => '_zipcart_phpzip',
  );
  return $methods;
}

/**
 * Return an array of zip methods
 */
function _zipcart_get_available_methods() {
  foreach (module_implements('zipmethods') as $module) {
    $function = $module . '_zipmethods';
    if ($methods = $function()) {
      if (is_array($methods)) {
        foreach ($methods as $key => $method) {
          $avail_methods[$key] = $method;
        }
      }
    }
  }
  return $avail_methods;
}

/**
 * Add a file path to a user's $_SESSION. Check the user has permission to access the file here,
 * so we can warn if they do not.
 */
function zipcart_add_file_to_cart($ajax = FALSE) {
  $path_parts = func_get_args();
  // Remove AJAX flag.
  array_shift($path_parts);
  // FIXME: we can't add the file 'sites/default/files/AJAX/myfile.txt' to our cart (?)
  $path       = implode('/', $path_parts);
  $path       = str_replace(ZIPCART_PATH_ADD, '', $path);
  $path       = trim($path, '/');
  $filename   = basename($path);

  $success = FALSE;

  $headers = module_invoke_all('file_download', $path);
  if (!in_array(-1, $headers)) {
    // OK, hook_file_download didn't object.
    $files = array($path);
    $files = module_invoke_all('filterzip', $files);

    if (!empty($files)) {
      $_SESSION['zipcart']['files'][] = $path;
      $success = TRUE;
    }
  }

  $_SESSION['zipcart']['files'] = array_unique($_SESSION['zipcart']['files']);
  $result = array(
    'cart' => $_SESSION['zipcart']['files'],
    'result' => $success,
  );
  if ($ajax) {
    die(drupal_json($result));
  }
  else {
    if ($success) {
      drupal_set_message(t('The file %filename has been added to your cart. !download', array('%filename' => check_plain($filename), '!download' => l(t('Click here to download'), ZIPCART_PATH_GET))));
    }
    else {
      drupal_set_message(t('The file !filename could not be added to your cart.', array('!filename' => check_plain($filename))));
    }
    drupal_goto();
  }
}

/**
 * Get the files as a zip
 */
function zipcart_get_zip() {
  if (empty($_SESSION['zipcart']['files'])) {
    drupal_set_message(t('Sorry, there are no files queued for you to download.'));
    drupal_goto();
  }
  else {
    $files = $_SESSION['zipcart']['files'];
    $files = module_invoke_all('filterzip', $files);

    if (!empty($files)) {
      $zipcart_dir = file_directory_path() . '/' . variable_get('zipcart_cache', 'zipcart');
      if (file_check_directory($zipcart_dir, 1)) {
        $methods = _zipcart_get_available_methods();
        $zipmethod = variable_get('zipcart_zip_method', 'zip_builtin');
        if (isset($methods[$zipmethod])) {
          $zipfunction = $methods[$zipmethod]['callback'];
          if (!$zipfunction($files)) {
            return 'Download failed.';
          }
          else {
            drupal_set_message(t('Zip downloaded.'));
            return TRUE;
          }
        }
      }
    }
  }
}

/**
 * Preprocess the list of files.
 *
 * Don't ever share these files:
 *   $excluded = array( 'sites/.*settings.*php' );
 *
 * Only ever include these files:
 *   $included = array( 'sites/files/.*' );
 *
 * Always include a certain file:
 *   $add = array( 'sites/default/files/README.txt' );
 */
function zipcart_filterzip($files) {
  foreach ($files as $i => &$file) {
    if (!file_check_location($file, file_directory_path())) {
      watchdog('zipcart', 'Forbidding download of !file', array('!file' => $file), WATCHDOG_NOTICE);
      unset($files[$i]);
    }
  }
  return $files;
}

/**
 * Zip callback: PHP zip extension
 */
function _zipcart_phpzip($files) {
  $zip = new ZipArchive();
  $filename = tempnam(file_directory_temp(), 'zip');
  // $filename = file_directory_path() . '/' . variable_get('zipcart_cache','zipcart') . '/' . time() . '.zip';
  $zip_open = $zip->open($filename, ZIPARCHIVE::CREATE | ZIPARCHIVE::OVERWRITE);
  $zip->setArchiveComment('Generated by ZipCart for Drupal.');
  if ($zip_open === TRUE) {
    // Would be nice to handle duplicate filenames sensibly here.
    foreach ($files as $file) {
      if (file_exists($file)) {
        if ($zip->addFile(realpath($file), basename($file))) {
          // drupal_set_message(t('!file added to Zip.', array('!file' => $file)));
        }
        else {
          // drupal_set_message(t('!file could not be added to Zip.', array('!file' => $file)), 'error');
          watchdog('zipcart', 'Failed to add !file to Zip.', array('!file' => $file), WATCHDOG_ERROR);
        }
      }
      else {
        watchdog('zipcart', 'Failed to locate !file.', array('!file' => $file), WATCHDOG_ERROR);
        // drupal_set_message('!file not found.', array('!file' => $file), 'error');
      }
    }
    $zip->close();
    $headers = module_invoke_all('file_download', $filename);
    if (in_array(-1, $headers)) {
      return drupal_access_denied();
    }
    // Remove any content-disposition headers here.
    if (count($headers)) {
      foreach ($headers as $k => $header) {
        if (stristr($header, 'Content-Disposition:') === 0 ||
            stristr($header, 'Content-Type:') === 0) {
          unset($headers[$k]);
        }
      }
    }
    $zip_filename = _zipcart_zip_filename();
    $headers[] = 'Content-Type: ' . file_get_mimetype($zip_filename);
    $headers[] = 'Content-Disposition: attachment; filename="' . $zip_filename . '"';
    // FIXME: it would be nice to wait until the file transfer completes before
    // we clear the files out of the session. However, if we do that, the user
    // can't add new files to their cart until the zip is downloaded. So we'll
    // do this first.
    $files = $_SESSION['zipcart']['files'];
    $_SESSION['zipcart']['files'] = array();
    register_shutdown_function('_zipcart_download_complete', $filename, $files);
    file_transfer($filename, $headers);
  }
  else {
    drupal_set_message(t('Unable to create file !filename.', array('!filename' => check_plain($filename))), 'error');
    drupal_access_denied();
    return FALSE;
  }
}

/**
 * Invoke hook_zipcart_download_complete() when download completed.
 */
function _zipcart_download_complete($filename, $files) {
  module_invoke_all('zipcart_download_complete', $filename, $files);
}

/**
 * Generate a suitable filename for the zip.
 */
function _zipcart_zip_filename() {
  $filename = 'Files - ' . date('Y-m-d_Hi') . '.zip';
  return $filename;
}

/**
 * Obtain correct path to return user to after adding file to cart.
 */
function _zipcart_get_destination_alias() {
  if (isset($_REQUEST['destination'])) {
    return 'destination=' . urlencode(drupal_get_path_alias($_REQUEST['destination']));
  }
  else {
    // Use $_GET here to retrieve the original path in source form.
    $path = isset($_GET['q']) ? $_GET['q'] : '';
    $query = drupal_query_string_encode($_GET, array('q'));
    if ($query != '') {
      $path .= '?' . $query;
    }
    return 'destination=' . urlencode(drupal_get_path_alias($path));
  }
}

/**
 * Theme function to generate a download link.
 */
function theme_zipcart_download($text, $path, $options = array()) {
  $default_options = array(
    'attributes' => array(
      'class' => 'zipcart',
    ),
    'query' => _zipcart_get_destination_alias(),
  );
  $options = array_merge($default_options, $options);
  return l($text, ZIPCART_PATH_ADD . '/' . $path, $options);
}

/**
 * Implements hook_zipcart_download_complete().
 *
 * Clean up built zips as required.
 */
function zipcart_zipcart_download_complete($filename, $files) {
  unlink($filename);
}

/**
 * Preprocess zipcart_block_downloads().
 */
function zipcart_preprocess_zipcart_block_downloads(&$variables) {
  drupal_add_js(drupal_get_path('module', 'zipcart') . '/zipcart.js');
  $settings = array(
    'zipcart' => array(
      'path_add' => ZIPCART_PATH_ADD,
      'path_add_ajax' => ZIPCART_PATH_ADD . '/AJAX',
    ),
  );
  drupal_add_js(, 'setting');
  $variables['count'] = (!empty($_SESSION['zipcart']['files'])) ? sizeof($_SESSION['zipcart']['files']) : 0;
  $variables['files'] = (!empty($_SESSION['zipcart']['files'])) ? $_SESSION['zipcart']['files'] : NULL;
}
